# https://hub.docker.com/_/nginx
FROM nginx

# This line links GHCR.io with the repository.
LABEL org.opencontainers.image.source=https://github.com/ussjoin/weft/tree/main/containers/weft_dashboard

COPY site /usr/share/nginx/html