name: Build Docker Container
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Container to Build'
        required: true
        default: 'weft_time'
  push:
    branches: main
    # file paths to consider in the event. Optional; defaults to all.
    paths:
      - 'containers/**'
jobs:
  build_container:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      -
        run: echo ${{ github.event }}
