---
- hosts: "{{ hostname }}"
  tasks:
    - name: Update Packages
      apt: upgrade=dist update_cache=true
      become: yes
    - name: Update raspi-config
      apt: pkg=raspi-config state=present update_cache=true
      become: yes
    - name: Expand RootFS
      shell: raspi-config nonint do_expand_rootfs
      become: yes
    - name: Set Hostname
      shell: raspi-config nonint do_hostname {{ hostname }}.weft
      become: yes
    - name: Set Memory Split
      shell: raspi-config nonint do_memory_split 4
      become: yes
    - name: Set Time Zone
      shell: sudo raspi-config nonint do_change_timezone America/Los_Angeles
      become: yes
    - name: Set Locale
      shell: raspi-config nonint do_change_locale en_US.UTF-8
      become: yes
    - name: Set Keyboard
      shell: raspi-config nonint do_configure_keyboard us
      become: yes
    - name: Reboot the worker node (for kernel upgrades)
      become: yes
      reboot:
    - name: Install New Packages
      become: yes
      apt:
        state: present
        name:
          - docker.io
          - mosquitto-clients # used for send_temp
          - bc # used for send_temp
          - python3-docker # Used by Ansible Docker module
          - python3-openssl # Used by Ansible OpenSSL module
    - name: Add Pi to Docker Users
      user:
        name: pi
        groups: docker
        append: yes
      become: yes
    - name: Copy file with owner and permissions
      copy:
        src: ./files/send_temp
        dest: /home/pi/send_temp
        owner: pi
        group: pi
        mode: a+rx
    - name: Measure temperature, send it to MQTT every 5 minutes.
      cron:
        name: "Measure Temperature"
        minute: "*/5"
        state: present
        job: "/home/pi/send_temp"
