---
- hosts: all
  tasks:
    - name: Update all packages to their latest version
      become: yes
      ansible.builtin.apt:
        update_cache: yes
        upgrade: dist
    - name: Install New Packages
      become: yes
      ansible.builtin.apt:
        state: present
        name:
          - docker.io
          - mosquitto-clients # used for send_temp
          - bc # used for send_temp
          - python3-docker # Used by Ansible Docker module
          - python3-openssl # Used by Ansible OpenSSL module
          - vim 
          - screen
    - name: Add ludd to Docker Users
      user:
        name: ludd
        groups: docker
        append: yes
      become: yes