name: Build Docker Container
on:
  push:
    branches: 
      - main
    paths:
      - 'containers/**'
  # workflow_dispatch:
  #   inputs:
  #     name:
  #       description: 'Container to Build'
  #       required: true
  #       default: 'weft_time'
jobs:
  build_container:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      # -
      #   name: Login to GitHub Container Registry
      #   uses: docker/login-action@v1
      #   with:
      #     registry: ghcr.io
      #     username: ${{ github.repository_owner }}
      #     password: ${{ secrets.CR_PAT }}
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2 # Enable git diff-tree to work
      - 
        name: Get name of changed container(s)
        id: getnames
        run: echo "::set-output name=container_name::$(git diff-tree --no-commit-id --name-only -r ${{ github.event.after }} | grep -oE '^containers\/([^/]+)/' | cut -d'/' -f2)\n"
      -
        name: OK now output it
        run: echo ${{ steps.getnames.outputs.container_name }}
